### ISSUE TITLE
релизы в Github

### ISSUE THREAD

**Issue by kotleni** [y9san9/kotlogram2#18]
Публикуйте релизы в Github с собраными .jar

**Comment by y9san9** [comment]
@kotleni зачем

**Comment by kotleni** [comment]
@y9san9, что бы бибилиотеку можно было использовать вне Gradle или оффлайн

**Comment by y9san9** [comment]
ты можешь 
а) собрать его сам
б) вытащить его с джитпака
мне лень каждый раз собирать либу перед релизом

**Comment by kotleni** [comment]
Как можно вытащить с джитпака?

**Comment by y9san9** [comment]
@kotleni https://jitpack.io/com/github/y9san9/kotlogram2/beta-1-5/kotlogram2-beta-1-5-sources.jar
https://jitpack.io/com/github/y9san9/kotlogram2/beta-1-5/kotlogram2-beta-1-5.jar
